language: node_js
sudo: false
node_js:
- 4.1.1
branches:
  except:
  - g3sync
cache:
  directories:
  - node_modules
  - $HOME/.pub-cache
env:
  global:
  - KARMA_BROWSERS=DartiumWithWebPlatform
  - E2E_BROWSERS=Dartium
  - LOGS_DIR=/tmp/angular-build/logs
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - ARCH=linux-x64
  - TSDRC='{"token":"ef474500309daea53d5991b3079159a29520a40b"}'
  - secure: fq/U7VDMWO8O8SnAQkdbkoSe2X92PVqg4d044HmRYVmcf6YbO48+xeGJ8yOk0pCBwl3ISO4Q2ot0x546kxfiYBuHkZetlngZxZCtQiFT9kyId8ZKcYdXaIW9OVdw3Gh3tQyUwDucfkVhqcs52D6NZjyE2aWZ4/d1V4kWRO/LMgo=
  - secure: C/rL8kn+MpuT1aaHjLadhCqKnvJPM23BwHDzLTVIOQFt4GJRtfhKQQsp/GkohzMLXxxrRzkYQF240vDRWbwp7D4GiMr6agGrlUkdUOn+QCW8BWnVytdYPtK4q1VfvtWIRYlSS1WmMOFVSKqWyNymGvOmUSVLD+C8O655r2zOnk0=
  matrix:
  - MODE=js DART_CHANNEL=dev
matrix:
  allow_failures:
  - env: MODE=saucelabs DART_CHANNEL=dev
  - env: MODE=dart_experimental DART_CHANNEL=dev
addons:
  apt:
    packages:
    - libav-tools
  firefox: '38.0'
before_install:
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
- echo ${TSDRC} > .tsdrc
- export DISPLAY=:99.0
- export GIT_SHA=$(git rev-parse HEAD)
- ./scripts/ci/init_android.sh
- ./scripts/ci/install_dart.sh ${DART_CHANNEL} ${ARCH}
- if [[ -e SKIP_TRAVIS_TESTS ]]; then { cat SKIP_TRAVIS_TESTS ; exit 0; } fi
install:
- npm install -g npm@2.14.4
- npm --version
- du -sh ./node_modules || true
- npm install
before_script:
- mkdir -p $LOGS_DIR
- ./scripts/ci/presubmit-queue-setup.sh
- avconv -f x11grab -r 25 -s 1280x1024 -i :99.0 -threads 4 -qscale 0 $HOME/output-${MODE}-${DART_CHANNEL}.mpg &
script:
- ./scripts/ci/build_and_test.sh ${MODE}
after_failure:
- sleep 5
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- mkdir gh-pages
- cd gh-pages
- git init
- git remote add origin https://${GH_TOKEN}@github.com/zzo/zzo.github.io.git > /dev/null
- git checkout -B gh-pages
- cp $HOME/output-${MODE}-${DART_CHANNEL}.mpg .
- git add output-${MODE}-${DART_CHANNEL}.mpg
- ls -l
- git commit -m "video updated"
- git push origin gh-pages -fq > /dev/null
after_script:
- ./scripts/ci/print-logs.sh
- ./scripts/ci/after-script.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1ef62e23078036f9cee4
    - https://buildtimetrend.herokuapp.com/travis
    on_success: always
    on_failure: always
    on_start: false
  slack:
    secure: EP4MzZ8JMyNQJ4S3cd5LEPWSMjC7ZRdzt3veelDiOeorJ6GwZfCDHncR+4BahDzQAuqyE/yNpZqaLbwRWloDi15qIUsm09vgl/1IyNky1Sqc6lEknhzIXpWSalo4/T9ZP8w870EoDvM/UO+LCV99R3wS8Nm9o99eLoWVb2HIUu0=
deploy:
- provider: gcs
  access_key_id: GOOGIOQTDBEOPBUAWFZQ
  secret_access_key:
    secure: MEDggllZ5fw4wI9CEUi8WR6jKsKXqdRF/DLxSNC2JpzM5RlVeBm0uqjntYT1Cf1dASvQ2/+vZCUikL/3A48NcoEYRHXGmxu8D6t/SvleQD8Xv434xFOdsa2QqP/HiCtqCLOI5jJz1JVoB5nNyKKZ33ogTUL1LV1TfcrAioyizW8=
  bucket: angular2-snapshots
  skip_cleanup: true
  acl: public-read
  local-dir: deploy
  upload-dir: $TRAVIS_COMMIT/dart_stable
  on:
    repo: angular/angular
    condition: $MODE = dart && $DART_CHANNEL = stable
- provider: gcs
  access_key_id: GOOGIOQTDBEOPBUAWFZQ
  secret_access_key:
    secure: MEDggllZ5fw4wI9CEUi8WR6jKsKXqdRF/DLxSNC2JpzM5RlVeBm0uqjntYT1Cf1dASvQ2/+vZCUikL/3A48NcoEYRHXGmxu8D6t/SvleQD8Xv434xFOdsa2QqP/HiCtqCLOI5jJz1JVoB5nNyKKZ33ogTUL1LV1TfcrAioyizW8=
  bucket: angular2-snapshots
  skip_cleanup: true
  acl: public-read
  local-dir: deploy
  upload-dir: $TRAVIS_COMMIT/js
  on:
    repo: angular/angular
    condition: $MODE = js
