version: '3'
services:
  windows-env:
    build:
      context: ../../
      dockerfile: ./.buildkite/dockerfiles/windows-env.Dockerfile
  windows-test-cached:
    build:
      context: ../../
      dockerfile: ./.buildkite/dockerfiles/windows-test.Dockerfile
      args:
        COMMIT_SHA: "${BUILDKITE_COMMIT}"
        FROM_IMG: "gcr.io/internal-200822/angular-windows:master"
  windows-test-clean:
    build:
      context: ../../
      dockerfile: ./.buildkite/dockerfiles/windows-test.Dockerfile
      args:
        COMMIT_SHA: "${BUILDKITE_COMMIT}"
