defaults: &defaults
  working_directory: ~/ng
  docker:
    - image: angular/ngcontainer

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}

      - run: npm install
      - run: ./node_modules/.bin/gulp lint

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: angular-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}

      - run: bazel run @io_bazel_rules_typescript_node//:bin/npm install
      - run: bazel build ...
      - save_cache:
          key: angular-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}
          paths:
            - "node_modules"

workflows:
  version: 2
  default_workflow:
    jobs:
      - lint
      - build
