name: Déclaration de bug
description: Déclarez un bug dans la documentation de l'application angular.dev

body:
  - type: dropdown
    id: affected-scope
    attributes:
      label: Quel est le scope du bug?
      options:
          - traductions
          - application
          - GitHub
          - autre
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: is-regression
    attributes:
      label: Est-ce une régression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Merci de fournir les étapes pour reproduire le bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Si ce problème a provoqué une exception ou une erreur, veuillez la coller ici
      render: true

  - type: textarea
    id: other
    attributes:
      label: Autre information
