name: Demande de fonctionnalité
description: Demandez une nouvelle fonctionnalité pour la traduction de la documentation de angular.dev

body:
  - type: dropdown
    id: affected-scope
    attributes:
      label: Quel est le scope de la demande de fonctionnalité?
      options:
        - traductions
        - application
        - GitHub
        - autre
      multiple: false

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Solution proposée
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives envisagées
    validations:
      required: true
