name: benchmarks_external
environment:
  sdk: '>=1.4.0'
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  angular2:
    path: ../angular2
  polymer_js:
    git:
      url: git@github.com:dart-lang/polymer_js.git
      ref: 0.8.0-preview
transformers:
- angular:
    html_files:
      - web/src/naive_infinite_scroll/scroll_area.html
      - web/src/naive_infinite_scroll/scroll_item.html
